// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type ClientMeta, formDataBodySerializer, type Options as Options2, type RequestResult, type TDataShape } from './client';
import { client } from './client.gen';
import type { AddBuildData, AddBuildErrors, AddBuildResponses, GetBuildData, GetBuildErrors, GetBuildLogsData, GetBuildLogsErrors, GetBuildLogsResponses, GetBuildResponses, GetBuildsData, GetBuildsErrors, GetBuildsResponses, GetCoverageData, GetCoverageErrors, GetCoverageResponses, HealthCheckData, HealthCheckResponses, UploadBuildLogsData, UploadBuildLogsErrors, UploadBuildLogsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Health Check
 */
export const healthCheck = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckData, ThrowOnError>): RequestResult<HealthCheckResponses, unknown, ThrowOnError> => (options?.client ?? client).get<HealthCheckResponses, unknown, ThrowOnError>({ url: '/api/v1/health-check', ...options });

/**
 * Get Builds
 */
export const getBuilds = <ThrowOnError extends boolean = false>(options?: Options<GetBuildsData, ThrowOnError>): RequestResult<GetBuildsResponses, GetBuildsErrors, ThrowOnError> => (options?.client ?? client).get<GetBuildsResponses, GetBuildsErrors, ThrowOnError>({ url: '/api/v1/builds', ...options });

/**
 * Add Build
 */
export const addBuild = <ThrowOnError extends boolean = false>(options: Options<AddBuildData, ThrowOnError>): RequestResult<AddBuildResponses, AddBuildErrors, ThrowOnError> => (options.client ?? client).post<AddBuildResponses, AddBuildErrors, ThrowOnError>({
    url: '/api/v1/builds',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Build
 */
export const getBuild = <ThrowOnError extends boolean = false>(options: Options<GetBuildData, ThrowOnError>): RequestResult<GetBuildResponses, GetBuildErrors, ThrowOnError> => (options.client ?? client).get<GetBuildResponses, GetBuildErrors, ThrowOnError>({ url: '/api/v1/builds/{id}', ...options });

/**
 * Get Build Logs
 */
export const getBuildLogs = <ThrowOnError extends boolean = false>(options: Options<GetBuildLogsData, ThrowOnError>): RequestResult<GetBuildLogsResponses, GetBuildLogsErrors, ThrowOnError> => (options.client ?? client).get<GetBuildLogsResponses, GetBuildLogsErrors, ThrowOnError>({ url: '/api/v1/builds/{id}/logs', ...options });

/**
 * Upload Build Logs
 */
export const uploadBuildLogs = <ThrowOnError extends boolean = false>(options: Options<UploadBuildLogsData, ThrowOnError>): RequestResult<UploadBuildLogsResponses, UploadBuildLogsErrors, ThrowOnError> => (options.client ?? client).put<UploadBuildLogsResponses, UploadBuildLogsErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/api/v1/builds/{id}/logs',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Get Coverage
 *
 * `interval` is an ISO 8601 duration, e.g. P1W or P1D.
 */
export const getCoverage = <ThrowOnError extends boolean = false>(options?: Options<GetCoverageData, ThrowOnError>): RequestResult<GetCoverageResponses, GetCoverageErrors, ThrowOnError> => (options?.client ?? client).get<GetCoverageResponses, GetCoverageErrors, ThrowOnError>({ url: '/api/v1/stats/coverage', ...options });
