// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * BuildCreate
 */
export type BuildCreate = {
    /**
     * Package Name
     */
    package_name: string;
    /**
     * Success
     */
    success: boolean;
    /**
     * Timestamp
     */
    timestamp: string;
    /**
     * Architecture
     */
    architecture: string;
    /**
     * Buildbot
     */
    buildbot: string;
    /**
     * Failure Reason
     */
    failure_reason?: string | null;
};

/**
 * BuildPublic
 */
export type BuildPublic = {
    /**
     * Package Name
     */
    package_name: string;
    /**
     * Success
     */
    success: boolean;
    /**
     * Timestamp
     */
    timestamp: string;
    /**
     * Architecture
     */
    architecture: string;
    /**
     * Buildbot
     */
    buildbot: string;
    /**
     * Failure Reason
     */
    failure_reason?: string | null;
    /**
     * Id
     */
    id: number;
};

/**
 * Builds
 */
export type Builds = {
    /**
     * Total
     */
    total: number;
    /**
     * Items
     */
    items: Array<BuildPublic>;
};

/**
 * CoveragePoint
 */
export type CoveragePoint = {
    /**
     * Snapshot
     */
    snapshot: string;
    /**
     * Architecture
     */
    architecture: string;
    /**
     * Coverage
     */
    coverage: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type HealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health-check';
};

export type HealthCheckResponses = {
    /**
     * Response Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type HealthCheckResponse = HealthCheckResponses[keyof HealthCheckResponses];

export type GetBuildsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Success
         */
        success?: boolean | null;
    };
    url: '/api/v1/builds';
};

export type GetBuildsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetBuildsError = GetBuildsErrors[keyof GetBuildsErrors];

export type GetBuildsResponses = {
    /**
     * Successful Response
     */
    200: Builds;
};

export type GetBuildsResponse = GetBuildsResponses[keyof GetBuildsResponses];

export type AddBuildData = {
    body: BuildCreate;
    path?: never;
    query?: never;
    url: '/api/v1/builds';
};

export type AddBuildErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddBuildError = AddBuildErrors[keyof AddBuildErrors];

export type AddBuildResponses = {
    /**
     * Successful Response
     */
    200: BuildPublic;
};

export type AddBuildResponse = AddBuildResponses[keyof AddBuildResponses];

export type GetBuildData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: number;
    };
    query?: never;
    url: '/api/v1/builds/{id}';
};

export type GetBuildErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetBuildError = GetBuildErrors[keyof GetBuildErrors];

export type GetBuildResponses = {
    /**
     * Successful Response
     */
    200: BuildPublic;
};

export type GetBuildResponse = GetBuildResponses[keyof GetBuildResponses];

export type GetCoverageData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Start
         */
        start?: string;
        /**
         * End
         */
        end?: string;
        /**
         * Interval
         */
        interval?: string;
    };
    url: '/api/v1/stats/coverage';
};

export type GetCoverageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCoverageError = GetCoverageErrors[keyof GetCoverageErrors];

export type GetCoverageResponses = {
    /**
     * Response Get Coverage
     *
     * Successful Response
     */
    200: Array<CoveragePoint>;
};

export type GetCoverageResponse = GetCoverageResponses[keyof GetCoverageResponses];
