"""Added builds table

Revision ID: 7e6107be32e4
Revises: 
Create Date: 2026-07-18 12:00:11.683886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '7e6107be32e4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('build',
    sa.Column('package_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('architecture', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('buildbot', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('failure_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_build_architecture'), 'build', ['architecture'], unique=False)
    op.create_index(op.f('ix_build_buildbot'), 'build', ['buildbot'], unique=False)
    op.create_index(op.f('ix_build_package_name'), 'build', ['package_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_build_package_name'), table_name='build')
    op.drop_index(op.f('ix_build_buildbot'), table_name='build')
    op.drop_index(op.f('ix_build_architecture'), table_name='build')
    op.drop_table('build')
    # ### end Alembic commands ###
