"""Added buildbot table

Revision ID: aaab0f4362ee
Revises: 7e6107be32e4
Create Date: 2026-08-23 15:46:30.963667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'aaab0f4362ee'
down_revision: Union[str, Sequence[str], None] = '7e6107be32e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildbot',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_buildbot_token_hash'), 'buildbot', ['token_hash'], unique=True)
    op.execute(sa.text("""
        INSERT INTO buildbot (name, enabled, token_hash)
        SELECT DISTINCT buildbot, false, 'migrated-without-token'
        FROM build
    """))
    op.create_foreign_key(
        'fk_build_buildbot', 'build', 'buildbot', ['buildbot'], ['name']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_build_buildbot', 'build', type_='foreignkey')
    op.drop_table('buildbot')
    # ### end Alembic commands ###
